"""add avatar_url and role to autonomous agent

Revision ID: 02c109dfb4b5
Revises: 1d67807fe498
Create Date: 2025-07-16 14:57:46.814317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c109dfb4b5'
down_revision: Union[str, Sequence[str], None] = '1d67807fe498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autonomous_agents', sa.Column('avatar_url', sa.String(length=256), nullable=True))
    op.add_column('autonomous_agents', sa.Column('role', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autonomous_agents', 'role')
    op.drop_column('autonomous_agents', 'avatar_url')
    # ### end Alembic commands ###
