"""add comprehensive features tables (voice/face/tts/model/api_key/analytics/session/automation/preferences)

Revision ID: 519d4d6beabf
Revises: 537afd6eae61
Create Date: 2025-07-16 20:27:04.845394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519d4d6beabf'
down_revision: Union[str, Sequence[str], None] = '537afd6eae61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.String(length=32), nullable=True))
    op.add_column('notifications', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'data')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
