"""add assigned_agent_id to evolution suggestion

Revision ID: 537afd6eae61
Revises: 96ac923ac7d0
Create Date: 2025-07-16 15:10:46.718832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537afd6eae61'
down_revision: Union[str, Sequence[str], None] = '96ac923ac7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evolution_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_agent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_assigned_agent_id', 'autonomous_agents', ['assigned_agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evolution_suggestions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assigned_agent_id', type_='foreignkey')
        batch_op.drop_column('assigned_agent_id')
    # ### end Alembic commands ###
