"""add suggestion message table for threaded discussions

Revision ID: 96ac923ac7d0
Revises: 02c109dfb4b5
Create Date: 2025-07-16 15:08:52.254693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ac923ac7d0'
down_revision: Union[str, Sequence[str], None] = '02c109dfb4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['autonomous_agents.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['suggestion_messages.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['evolution_suggestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion_messages')
    # ### end Alembic commands ###
